---

# Dependencies specify other packages that your package needs in order to work.# For information on the generic Dart part of this file, see the  # An image asset can refer to one or more resolution-specific "variants", see  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # https://flutter.dev/assets-and-images/#resolution-aware

# following page: https://dart.dev/tools/pub/pubspec

dependencies:
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.8
  simple_gradient_text: 1.2.4
  chat_bubbles: ^1.3.1
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^1.1.6
  google_maps_flutter: ^2.1.1
  http: ^1.1.0
  path_provider: ^2.0.5
  flutter_pdfview: ^1.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^14.0.1
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: "assets/images/logo/small-width-blue-edgar-logo.png"
environment:
  sdk: '>=2.18.4 <3.0.0'
flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Regular.ttf
        - asset: assets/font/Raleway-Medium.ttf
        - asset: assets/font/Raleway-Italic.ttf
  assets:
    - assets/images/logo/
    - assets/images/utils/
    - .env  # The following line ensures that the Material Icons font is
name: prototype_1
publish_to: none
version: 1.0.0+1
