---

# Dependencies specify other packages that your package needs in order to work.# For information on the generic Dart part of this file, see the  # An image asset can refer to one or more resolution-specific "variants", see  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # https://flutter.dev/assets-and-images/#resolution-aware

# following page: https://dart.dev/tools/pub/pubspec

dependencies:
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter:
    sdk: flutter
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.18.4 <3.0.0'
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
  assets:
    - assets/images/logo/
    - .env  # The following line ensures that the Material Icons font is
name: prototype_1
publish_to: none
version: 1.0.0+1
